ParzialmenteIdeaBundle_nuova:
    pattern:  /nuova
    defaults: { _controller: ParzialmenteIdeaBundle:Default:nuova }

ParzialmenteIdeaBundle_idea:
    pattern: /{id}/{slug}
    defaults: { _controller: ParzialmenteIdeaBundle:Default:mostra }
